workflow reusable modification

diff --git a/.github/workflows/reuse-deploy.yaml b/.github/workflows/reuse-deploy.yaml
--- a/.github/workflows/reuse-deploy.yaml
+++ b/.github/workflows/reuse-deploy.yaml
@@ -29,6 +29,9 @@ on:
       ENVIRONMENT: 
         required: true
         type: string
+      ROUTE: 
+        required: true
+        type: string
     secrets:
       gcp_credentials:
         required: true
@@ -42,7 +45,7 @@ jobs:
     runs-on: ubuntu-latest
     environment:
       name: ${{inputs.ENVIRONMENT}}
-      url: http://${{ steps.ingress_ip.outputs.INGRESS_IP }}/${{env.ROUTE}}
+      url: http://${{ steps.ingress_ip.outputs.INGRESS_IP }}/${{inputs.ROUTE}}
     outputs:
       INGRESS_URL: ${{ steps.ingress_ip.outputs.INGRESS_IP }}
     permissions:
@@ -114,11 +117,26 @@ jobs:
         INGRESS_IP=$(kubectl get ingress -o json | jq -r '.items[0].status.loadBalancer.ingress[0].ip')
         echo "INGRESS_IP=$INGRESS_IP" >> $GITHUB_OUTPUT
 
-  Slack-notification:
+
+  Run-staging-Integration-Testing:
+    if: github.ref == 'refs/heads/main'
     runs-on: ubuntu-latest
-    needs: [reuse-deploy]
+    needs: reuse-deploy
     steps:
-    - name: Check job1 status
+    - name: Check previous job
+      run: echo "hello ${{ needs.reuse-deploy.outcome }}"
+
+    - name: Run application Testing using curl to ingress ip
+      env:
+        URL: ${{needs.staging-deploy.outputs.INGRESS_URL}}
       run: |
-        echo "Job 1 outcome: Hello!!!!!!!!!!!!!!"
+        echo "http://$URL/$ROUTE"
+        echo "-------------------------"
+        status_code=$(curl -i -s http://$URL/${{inputs.ROUTE}} | grep HTTP | awk '{print $2}')
+        if [[ $status_code -eq 200 ]]; then
+          echo "API endpoint is accessible"
+        else
+          echo "404 Error: Resource not found"
+          exit 1  # Exit with an error code to indicate failure
+        fi
           
