Hot fix

diff --git a/.github/workflows/sonarqube.yaml b/.github/workflows/sonarqube.yaml
--- a/.github/workflows/sonarqube.yaml
+++ b/.github/workflows/sonarqube.yaml
@@ -175,6 +175,7 @@ jobs:
 
   # Job 4: Redeploy Kubernetes Deployment
   dev-deploy:
+    # if: ${{ startsWith(github.ref, 'refs/heads/feature') || github.ref == 'refs/heads/dev' }}
     runs-on: ubuntu-latest
     # needs: build-and-scan
     environment:
@@ -203,8 +204,8 @@ jobs:
       id: get-credentials
       uses: google-github-actions/get-gke-credentials@v1
       with:
-        cluster_name: agric-os-prod-v2
-        location: europe-west3-a
+        cluster_name: ${{env.GKE_CLUSTER}}
+        location: ${{env.GKE_ZONE}}
 
     - name: Replace token in manifest files
       uses: cschleiden/replace-tokens@v1
@@ -265,6 +266,7 @@ jobs:
 
 
   Run-Integration-Testing:
+    # if: ${{ startsWith(github.ref, 'refs/heads/feature') || github.ref == 'refs/heads/dev' }}
     runs-on: ubuntu-latest
     needs: dev-deploy
     steps:
@@ -282,6 +284,114 @@ jobs:
           exit 1  # Exit with an error code to indicate failure
         fi
 
-  # Add environment with url variable 
-  # Add integration path with url of the app for curl testing with response check
-  # If statement and different need
+
+  # Job 4: Redeploy Kubernetes Deployment
+  staging-deploy:
+    if: github.ref == "refs.heads.main"
+    runs-on: ubuntu-latest
+    # needs: build-and-scan
+    environment:
+      name: staging
+      url: http://${{ steps.ingress_ip.outputs.INGRESS_IP }}/${{env.ROUTE}}
+    outputs:
+      INGRESS_URL: ${{ steps.ingress_ip.outputs.INGRESS_IP }}
+    permissions:
+      contents: 'read'
+      id-token: 'write' # Needed for OIDC token generation
+
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+
+    - name: Authenticate to Google Cloud
+      id: gcp-auth
+      uses: google-github-actions/auth@v1
+      with:
+        credentials_json: '${{ secrets.gcp_credentials }}'
+        # workload_identity_provider: '/projects/524687905739/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
+        # service_account: 'agricos-prod-access-from-githu@agri-os-prod.iam.gserviceaccount.com'
+        # audience: "//iam.googleapis.com/projects/agri-os-prod /locations/global/workloadIdentityPools/github-pool/providers/github-provider"
+
+    - name: Get GKE Credentials
+      id: get-credentials
+      uses: google-github-actions/get-gke-credentials@v1
+      with:
+        cluster_name: ${{env.GKE_CLUSTER}}
+        location: ${{env.GKE_ZONE}}
+
+    - name: Replace token in manifest files
+      uses: cschleiden/replace-tokens@v1
+      with:
+        tokenPrefix: '_{_'
+        tokenSuffix: '_}_'
+        files: '["applications/service-envs/dev/*.yaml"]'
+      env:
+        NAMESPACE: ${{vars.NAMESPACE}}
+        REPLICAS: ${{vars.REPLICAS}}
+        IMAGE: ${{env.IMAGE}}:${{env.TAG}}
+
+    - name: Install kubectl
+      uses: azure/setup-kubectl@v3
+      with:
+        version: 'latest'
+
+    - name: Install jq
+      run: sudo apt-get update && sudo apt-get install -y jq
+
+
+    - name: Create or update application secret
+      run: |
+        echo "apiVersion: v1
+        kind: Secret
+        metadata:
+          name: farming-secret
+        type: Opaque
+        stringData:
+          DB_HOST: ${{ vars.DB_HOST }}
+          DB_USERNAME: ${{ vars.DB_USERNAME }}
+          DB_PASSWORD: ${{ vars.DB_PASSWORD }}" | kubectl apply -f -
+
+        kubectl get secret farming-secret -o yaml
+
+
+    # The KUBECONFIG env var is automatically exported and picked up by kubectl.
+    - name: Deploy manifest
+      run: 'kubectl apply -f applications/service-envs/dev'
+
+    - name: Retrieve ingress Host Url IP
+      id: ingress_ip
+      run: |
+        INGRESS_IP=$(kubectl get ingress -o json | jq -r '.items[0].status.loadBalancer.ingress[0].ip')
+        echo "INGRESS_IP=$INGRESS_IP" >> $GITHUB_OUTPUT
+
+    - name: Slack Notification
+      uses: rtCamp/action-slack-notify@v2
+      env:
+        SLACK_CHANNEL: core-api-alert
+        SLACK_COLOR: ${{ job.status }}
+        SLACK_ICON: https://github.com/rtCamp.png?size=48
+        SLACK_MESSAGE: "${{ github.event.head_commit.message }} || App_version:${{ env.APP_VERSION }} "
+        SLACK_TITLE: Commit Message
+        SLACK_USERNAME: rtCamp
+        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK  }}
+      if: always()
+
+
+  Run-staging-Integration-Testing:
+    if: github.ref == "refs.heads.main"
+    runs-on: ubuntu-latest
+    needs: staging-deploy
+    steps:
+    - name: Run application Testing using curl to ingress ip
+      env:
+        URL: ${{needs.dev-deploy.outputs.INGRESS_URL}}
+      run: |
+        echo "http://$URL/$ROUTE"
+        echo "-------------------------"
+        status_code=$(curl -i -s http://$URL/$ROUTE | grep HTTP | awk '{print $2}')
+        if [[ $status_code -eq 200 ]]; then
+          echo "API endpoint is accessible"
+        else
+          echo "404 Error: Resource not found"
+          exit 1  # Exit with an error code to indicate failure
+        fi
